spring:
  application:
    name: wallet-interaction-service
  datasource:
    url: jdbc:mysql://localhost:3306/wis
    username: wis-db-user
    password: wis-db-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: ${message-broker.rabbitmq.host}
    port: ${message-broker.rabbitmq.amqp-port}
    username: ${message-broker.rabbitmq.admin-username}
    password: ${message-broker.rabbitmq.admin-password}
message-broker:
  rabbitmq:
    host: localhost
    amqp-port: 5672
    stream-port: 5552
    admin-username: test-rabbitmq-user
    admin-password: test-rabbitmq-password